# docker-compose up -d

version: '3.2'
networks:
  gallery-network:
    driver: bridge
services:
  postgres:
    image: postgres
    container_name:  gallery-postgres
    environment:
      POSTGRES_DB: gallery_api
      POSTGRES_USER: gallery
      POSTGRES_PASSWORD: Tartans@@1
    volumes:
      - ./_data:/var/lib/postgresql/data
    logging:
      options:
        max-size: "100m"
        max-file: "5"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gallery"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - gallery-network
    restart: always

  gallery-api:
    image: gallery/api
    container_name: gallery-api
    depends_on:
      - postgres
    ports:
      - "4722:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    networks:
      - gallery-network
    restart: always
